import os
from pathlib import Path

from dotenv import load_dotenv
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm
from typing import Optional
import google.auth

# Load environment variables
root_dir = Path(__file__).parent.parent
dotenv_path = root_dir / ".env"
load_dotenv(dotenv_path=dotenv_path)

# Configure Google Cloud
try:
    _, project_id = google.auth.default()
    os.environ.setdefault("GOOGLE_CLOUD_PROJECT", project_id)
except Exception:
    pass

os.environ.setdefault("GOOGLE_CLOUD_LOCATION", "europe-west1")

# Configure model connection
gemma_model_name = os.getenv("GEMMA_MODEL_NAME", "gemma3:270m")
api_base = os.getenv("OLLAMA_API_BASE", "localhost:10010")  # Location of Ollama server

# Define a function that processes the input file
def process_file_content(file_path: str) -> str:
    """
    Reads the content of a specified file and returns it.
    Args:
        file_path (str): The path to the input file.
    Returns:
        str: The content of the file.
    """
    try:
        with open(file_path, 'r') as f:
            content = f.read()
        return f"File content: {content}"
    except FileNotFoundError:
        return f"Error: File not found at {file_path}"
    except Exception as e:
        return f"An error occurred while reading the file: {e}"

# Convertor Agent - GPU-accelerated conversational assistant
conversion_agent = Agent(
   model=LiteLlm(model=f"ollama_chat/{gemma_model_name}", api_base=api_base),
   name="Conversion_Agent",
   description="Converting the COBOL Program to Python language",
   instruction="""You are 'Gem', a friendly, knowledgeable, and enthusiastic programmer. 
   Your main goal is to convert COBOL programs to Python language.

   You can provide information and interesting facts about technical topics, such as:
   - Field sizes, copybooks
   - Technical functionality of the program


   Always answer based on your general knowledge about the COBOL language.""",
   tools=[process_file_content],  # Gemma focuses on conversational capabilities
)

converter_agent = conversion_agent


reviewer_agent = Agent(
   model=LiteLlm(model=f"ollama_chat/{gemma_model_name}", api_base=api_base),
   name="Reviewer_Agent",
   description="Review the functionality of Python Program by comparing the COBOL program",
   instruction="""You are 'Gem', a friendly, knowledgeable, and enthusiastic Python programmer. 
   Your main goal is to review the Python program which is generated by root agent and decide the functionality of the program.

   You can provide information and interesting facts about the program.""",
   tools=[],  # Gemma focuses on conversational capabilities
)

review_agent = reviewer_agent

# Root agent acting as a Trip Planner coordinator
root_agent = Agent(
    model=LiteLlm(model=f"ollama_chat/{gemma_model_name}", api_base=api_base),
    name="COBOL_To_Python_Convertor",
    instruction=f"""
    Acts as a comprehensive converter.
    - Use the conversion_agent to convert the program from COBOL to python
    - Use the reviewer_agent to review the converted python program, validate the logic
    ...
    """,
    sub_agents=[converter_agent, review_agent] # The coordinator manages these sub-agents
)

async def run_file_processing_example():
    # In a real application, you would interact with the agent through a session
    # For demonstration, we'll simulate an agent call.
    # The LLM would internally call the tool with the provided file path.
    user_message = "Please read the content of 'my_input_file.cbl'."
    print(f"User: {user_message}")

    # Simulate the agent's response, which would involve calling the tool
    # In a live ADK environment, the agent would interpret the prompt
    # and call the `process_file_content` tool with "my_input_file.txt".
    # The tool's output would then be returned as part of the agent's response.
    
    # For this example, we'll directly call the tool to illustrate the input.
    # In a full ADK setup, the agent would orchestrate this.
    file_path_to_process = "my_input_file.cbl"
    tool_result = process_file_content(file_path_to_process)
    print(f"Agent's simulated tool output: {tool_result}")

# To run the example (requires an async context)
import asyncio
asyncio.run(run_file_processing_example())